// flow-typed signature: fddbf93b1bf9cae2c5e25dd2dd537ae2
// flow-typed version: <<STUB>>/simplex-solver_v0.0.3/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simplex-solver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simplex-solver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simplex-solver/app/common/index' {
  declare module.exports: any;
}

declare module 'simplex-solver/app/common/uiCheckbox' {
  declare module.exports: any;
}

declare module 'simplex-solver/app/common/uiDropdown' {
  declare module.exports: any;
}

declare module 'simplex-solver/app/common/uiPopup' {
  declare module.exports: any;
}

declare module 'simplex-solver/app/components/index' {
  declare module.exports: any;
}

declare module 'simplex-solver/app/components/simplex' {
  declare module.exports: any;
}

declare module 'simplex-solver/app/index' {
  declare module.exports: any;
}

declare module 'simplex-solver/assets/js/application' {
  declare module.exports: any;
}

declare module 'simplex-solver/assets/js/config/date' {
  declare module.exports: any;
}

declare module 'simplex-solver/assets/js/config/jquery' {
  declare module.exports: any;
}

declare module 'simplex-solver/assets/js/config/string' {
  declare module.exports: any;
}

declare module 'simplex-solver/config/environment' {
  declare module.exports: any;
}

declare module 'simplex-solver/config/index' {
  declare module.exports: any;
}

declare module 'simplex-solver/gulpfile' {
  declare module.exports: any;
}

declare module 'simplex-solver/server/index' {
  declare module.exports: any;
}

declare module 'simplex-solver/server/worker' {
  declare module.exports: any;
}

declare module 'simplex-solver/src/equation' {
  declare module.exports: any;
}

declare module 'simplex-solver/src/index' {
  declare module.exports: any;
}

declare module 'simplex-solver/test/env' {
  declare module.exports: any;
}

declare module 'simplex-solver/test/simplex' {
  declare module.exports: any;
}

declare module 'simplex-solver/util/object' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simplex-solver/app/common/index.js' {
  declare module.exports: $Exports<'simplex-solver/app/common/index'>;
}
declare module 'simplex-solver/app/common/uiCheckbox.js' {
  declare module.exports: $Exports<'simplex-solver/app/common/uiCheckbox'>;
}
declare module 'simplex-solver/app/common/uiDropdown.js' {
  declare module.exports: $Exports<'simplex-solver/app/common/uiDropdown'>;
}
declare module 'simplex-solver/app/common/uiPopup.js' {
  declare module.exports: $Exports<'simplex-solver/app/common/uiPopup'>;
}
declare module 'simplex-solver/app/components/index.js' {
  declare module.exports: $Exports<'simplex-solver/app/components/index'>;
}
declare module 'simplex-solver/app/components/simplex.js' {
  declare module.exports: $Exports<'simplex-solver/app/components/simplex'>;
}
declare module 'simplex-solver/app/index.js' {
  declare module.exports: $Exports<'simplex-solver/app/index'>;
}
declare module 'simplex-solver/assets/js/application.js' {
  declare module.exports: $Exports<'simplex-solver/assets/js/application'>;
}
declare module 'simplex-solver/assets/js/config/date.js' {
  declare module.exports: $Exports<'simplex-solver/assets/js/config/date'>;
}
declare module 'simplex-solver/assets/js/config/jquery.js' {
  declare module.exports: $Exports<'simplex-solver/assets/js/config/jquery'>;
}
declare module 'simplex-solver/assets/js/config/string.js' {
  declare module.exports: $Exports<'simplex-solver/assets/js/config/string'>;
}
declare module 'simplex-solver/config/environment.js' {
  declare module.exports: $Exports<'simplex-solver/config/environment'>;
}
declare module 'simplex-solver/config/index.js' {
  declare module.exports: $Exports<'simplex-solver/config/index'>;
}
declare module 'simplex-solver/gulpfile.js' {
  declare module.exports: $Exports<'simplex-solver/gulpfile'>;
}
declare module 'simplex-solver/server/index.js' {
  declare module.exports: $Exports<'simplex-solver/server/index'>;
}
declare module 'simplex-solver/server/worker.js' {
  declare module.exports: $Exports<'simplex-solver/server/worker'>;
}
declare module 'simplex-solver/src/equation.js' {
  declare module.exports: $Exports<'simplex-solver/src/equation'>;
}
declare module 'simplex-solver/src/index.js' {
  declare module.exports: $Exports<'simplex-solver/src/index'>;
}
declare module 'simplex-solver/test/env.js' {
  declare module.exports: $Exports<'simplex-solver/test/env'>;
}
declare module 'simplex-solver/test/simplex.js' {
  declare module.exports: $Exports<'simplex-solver/test/simplex'>;
}
declare module 'simplex-solver/util/object.js' {
  declare module.exports: $Exports<'simplex-solver/util/object'>;
}
